plugin_dirs = [
    '/home/jqwang/.wine/drive_c/Program Files/Common Files/VST3',
    '/home/jqwang/Dropbox/Music/Plugins/vst',
]
vst2_location = 'centralized'
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-7.17.r0.g6d46b1e1 ( TkG Staging Esync Fsync )'
yabridge_host_hash = -3094479323878875900
